apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "garage.fullname" . }}-config
data:
  garage.toml: |-
    metadata_dir = "{{ .Values.garage.metadataDir }}"
    data_dir = "{{ .Values.garage.dataDir }}"

    replication_mode = "{{ .Values.garage.replicationMode }}"

    rpc_bind_addr = "{{ .Values.garage.rpcBindAddr }}"
    # rpc_secret will be populated by the init container from a k8s secret object
    rpc_secret = "__RPC_SECRET_REPLACE__"

    bootstrap_peers = {{ .Values.garage.bootstrapPeers }}

    kubernetes_namespace = "{{ .Release.Namespace }}"
    kubernetes_service_name = "{{ include "garage.fullname" . }}"
    kubernetes_skip_crd = {{ .Values.garage.kubernetesSkipCrd }}

    [s3_api]
    s3_region = "{{ .Values.garage.s3.api.region }}"
    api_bind_addr = "[::]:3900"
    root_domain = "{{ .Values.garage.s3.api.rootDomain }}"

    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = "{{ .Values.garage.s3.web.rootDomain }}"
    index = "{{ .Values.garage.s3.web.index }}"