apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "garage.fullname" . }}
  labels:
    {{- include "garage.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "garage.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "garage.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "garage.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "garage.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3900
              name: s3-api
            - containerPort: 3902
              name: web-api
          volumeMounts:
            - name: meta
              mountPath: /mnt/meta
            - name: data
              mountPath: /mnt/data
            - name: etc
              mountPath: /etc/garage.toml
              subPath: garage.toml
          # TODO
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 3900
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 3900
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: etc
          configMap:
            name: {{ include "garage.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: meta
    spec:
      accessModes: [ "ReadWriteOnce" ]
    {{- if hasKey .Values.persistence.meta "storageClass" }}
      storageClassName: {{ .Values.persistence.meta.storageClass | quote }}
    {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.meta.size | quote }}
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
    {{- if hasKey .Values.persistence.data "storageClass" }}
      storageClassName: {{ .Values.persistence.data.storageClass | quote }}
    {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.data.size | quote }}
  {{- end }}
